### ISSUE TITLE
Not working on Angular 6 with multiple lazy-loaded modules...

### ISSUE THREAD

**Issue by pniel-cohen** [bovandersteene/ngx-breadcrumb#3]
Hi,
1. Thanks for sharing this module.
2. I tried to use it on an Angular 6 app that contains multiple lazy-loaded feature-modules & complex routing & it didn't work.
I think that I managed to solve the version issue by using .pipe() on the router.event, but it still throws errors while rendering.
Any idea?

**Comment by shivangT1994** [comment]
same issue. Please post help for this problem
